version: 2

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - builder: rust
    flags:
      - --release
      - --features=self_update
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin
      - x86_64-pc-windows-gnu
    id: "khelp"
    binary: khelp

archives:
  - formats: [ 'tar.gz' ]
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - none*
    name_template: >-
      {{ .ProjectName }}-{{ .Target }}
    builds:
      - khelp

changelog:
  disable: true

release:
  footer: >-
    ---
    Released by [GoReleaser](https://
